# Generated by Django 5.2.4 on 2025-08-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(default="en", max_length=25),
            preserve_default=False,
        ),
    ]
